Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [1]:
def vandermonde(N, x, increasing=False):
    '''N is the number of column required
       x is the array to be modified
       increasing shows wheather to keep the array left or right
    '''
    y = np.array([[j**(N-i-1) for i in range(0,N)] for j in x])
    if increasing == True :
        y = np.flip(y, axis=1)
    print(y)

In [2]:
import numpy as np
x = np.array([1,2,3,4])
N = 4
vandermonde(N, x)

[[ 1  1  1  1]
 [ 8  4  2  1]
 [27  9  3  1]
 [64 16  4  1]]


In [3]:
vandermonde(N, x, True)

[[ 1  1  1  1]
 [ 1  2  4  8]
 [ 1  3  9 27]
 [ 1  4 16 64]]


In [4]:
def moving_average(l, k):
    new_list = [float((l[i] + l[i+1] + l[i+2]+ l[i+3])/k) for i in range(len(l)-k+1)]
    print(new_list)

In [5]:
x = [i for i in range(10, 101, 10)]
k=4
moving_average(x, k)

[25.0, 35.0, 45.0, 55.0, 65.0, 75.0, 85.0]
